#!/usr/bin/env bash
../install_dotbot -c unix_desktop/desktop.conf.yaml
sudo pacman -S --needed  --noconfirm - < pacman/pkglist.txt
sudo ../install_dotbot -c unix_desktop/root_desktop.conf.yaml
if [ ! -d /usr/share/sddm/themes/sddm-sugar-candy ]; then
    sudo git clone https://github.com/Pietietjie/sddm-sugar-candy.git /usr/share/sddm/themes/sddm-sugar-candy --depth 1
    sudo pacman -S --needed sddm qt5-graphicaleffects qt5-quickcontrols2 qt5-svg qt5-wayland
    sudo chmod 777  /usr/share/sddm/themes/sddm-sugar-candy/Backgrounds/tokyo.jpg
    sudo chmod 777  /usr/share/sddm/themes/sddm-sugar-candy
fi
